source "https://rubygems.org"

ruby "3.4.9"

gem "rails", "~> 7.1.0"
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"
gem "jbuilder"
gem "rack-cors"
gem "bcrypt", "~> 3.1.7"

group :development, :test do
  gem "debug"
end
